### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/murnion-task-8#1]
**Sorrrrrii Felix!**

But you really did not observe that the _High-to-low_ routines should be global declarations, just as the C functions are global. This requires you to:
1) Declare `multiply` and `factorial` as global. _Hint_: search for the `globl` directive.
2) Follow the callee convensions. A callee must preserve the values of any utilized saved registers and the return address register using the stack.
_Stack operation macros_:
```mips
##
# Push value to application stack.
# PARAM: Registry with value.
##
.macro	PUSH (%reg)
	addi	$sp,$sp,-4              # decrement stack pointer (stack builds "downwards" in memory)
	sw	    %reg,0($sp)             # save value to stack
.end_macro

##
# Pop value from application stack.
# PARAM: Registry which to save value to.
##
.macro	POP (%reg)
	lw	    %reg,0($sp)             # load value from stack to given registry
	addi	$sp,$sp,4               # increment stack pointer (stack builds "downwards" in memory)
.end_macro
```

Otherwise, your _Sieve of Eratosthenes_ was fully acceptable!

Good luck!

**Comment by abdbla** [comment]
I think the multiply and factorial routines are global now...

As for part two, do you mean I _have_ to use the stack to save the return adress, instead of just using a temporary adress as I'm doing right now? I don't believe I utilize any saved registers in my code.

**Comment by violaso** [comment]
I can have oversight ;)
